### ISSUE TITLE
Ampliar con caso menor que cierto tamaño para el teorema de aproximación de Bernteins

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#25]

**Comment by JJ** [comment]
¿Un poco de contexto para los que no sepamos de qué estás hablando?

**Comment by BlancaCC** [comment]
Aunque parezca sorprendente por la poca claridad de este issue todavía recuerdo el motivo, procedo. a explicarlo por si se me acaba olvidando 😅

En el teorema de aproximación de Bernstein, del capítulo de teoría de aproximación la demostración no incluye un caso. 
El que contempla la cota de error cuando los nodos y la imagen a aproximar están cerca.

**Comment by JJ** [comment]
Las asociaciones las tienes que poner en el cuerpo. Simplemente edítalo para incluirlo. Y recuerda que no se puede crear (prácticamente) ningún issue que no esté relacionado con una HU (las excepciones serían issues de infraestructura o de corrección de errores)
