### ISSUE TITLE
Cambia nombre al repo

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#26]
Ponle un nombre de proyecto, o cualquier cosa más o menos original que se te ocurra.

**Comment by BlancaCC** [comment]
@JJ 👍 tienes toda la razón, gracias por la observación

**Comment by BlancaCC** [comment]
Ya se le ha puesto un nuevo nombre, ahora es "TFG-Estudio-de-las-redes-neuronales" He preferido mantener lo de TFG porque me parece esclarecedor para alguien de fuera en cuanto que puede hacerse una idea del nivel académico que va a encontrarse y lo de Estudio de las redes neuronales porque es en lo que estamos trabajando ahora.
