### ISSUE TITLE
Añade lo que has borrado del repo a .gitignore

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#35]
Como .DS_Store y .vscode. En general, la buena práctica es no añadirlo, y si se ha añadido, borrarlo y a continuación ponerlo en `.gitignore`.

Buena práctica adicional: Nunca uses `git add` . o `git add *`

https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/blob/710fa7dba1829e2b8e077e6b083d775608afa5bd/.gitignore#L1

**Comment by BlancaCC** [comment]
@JJ Sí, tienes razón y desde que me lo dijiste por primera vez lo estoy aplicando en todos los repos. Pero esta vez eran muchos archivos y me ha podido la tentación.

**Comment by BlancaCC** [comment]
Diría que se borró en el commit 710fa7dba1829e2b8e077e6b083d775608afa5bd , pero de todas formas en el siguiente commit que haga revisaré que no queda ninguno y actualizaré el gitignore
