### ISSUE TITLE
Nombres de ficheros

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#36]
Es una tontería, pero mira el nombre de este fichero.

https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/blob/710fa7dba1829e2b8e077e6b083d775608afa5bd/dudas/CuestioensYReflexiones.md?plain=1#L1

**Comment by BlancaCC** [comment]
@JJ Tomo nota para cambiarlo
