### ISSUE TITLE
Estudiar y desarrollar el artículos "Multilayer Feedforward Networks are Universal Approximators"

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#38]
Es necesario traducir los apartados que ya tenías escritos en inglés y terminar de completar los que te faltaban. 

Este issue se cerrará al acabar tal sección del proyecto.

**Comment by JJ** [comment]
Como te he comentado en #38, un issue debe plantear un problema. Yo diría que, igual que ahí, el problema es entender los conceptos y teoremas que demuestran que las redes multicapa son aproximadores universales, con el objetivo de poder crear supuestos más restrictivos y/o más precisos (lo que engarzaría con los objetivos del TFG; los issues que plantees siempre tienen, directa o indirectamente, ayudarte a progresar en los objetivos del TFG).
Por otro lado, está bien que en este caso incluyas un criterio de aceptación. En general, se tratará de un test que irá al sistema de integración continua, en este caso está bien el que has incluido (aunque no está claro a qué sección te refieres)

**Comment by BlancaCC** [comment]
Como matemática me gustaría conocer el motivo de la convergencia de las redes neuronales #50 y este artículo fue el primero publicado que lo consigue con éxito. 
Se escribirá como capítulo independiente sobre la convergencia de las redes neuronales. 
El criterio de aceptación será: 
- Redacción correcta.
- Aprobación del mismo por parte de los tutores.

**Comment by BlancaCC** [comment]
Este issue debió de cerrarse con el PR #67
