### ISSUE TITLE
[MFNAUA] Introducción

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#39]
- Objetivo del artículo.
- Comentar contexto histórico.
- Relevancia.

Nota, MFNAUA hace referencia a las siglas del artículo con el que estamos trabajando, Multilayer Feedforwars are Iniversal Approximators

**Comment by JJ** [comment]
En general, debes intentar que los issues siempre avancen hacia un objetivo y se formulen como un problema. También que pertenezcan a un milestone, como te he comentado. En este caso, yo diría que
1. Necesitas un milestone que consista en revisión bibliográfica, y que tenga como PMV una revisión escrita con los principales resultados y un sucinto estado del arte. Esto tendrá directametne la forma de un capítulo completo del TFG.

**Comment by BlancaCC** [comment]
Reformulo este issue: Como matemática me gustaría dejar clara las intenciones del artículo en cuestión, su relevancia y contexto histórico enquistamiento que surgió. 
Forma parte el objetivo de comprender las rrnn #50 y dará comienzo a un nuevo capítulo dentro de la memoria: "Las redes neuronales son aproximados universales".

**Comment by BlancaCC** [comment]
Reformulo este issue: Como matemática me gustaría dejar clara las intenciones del artículo en cuestión, su relevancia y contexto histórico enquistamiento que surgió.
Forma parte el objetivo de comprender las rrnn #50  y dará comienzo a un nuevo capítulo dentro de la memoria: "Las redes neuronales son aproximados universales".
El criterio de aceptación será: 
- Finalización del capítulo.
- Redacción correcta.
- Que sea aprobado por los tutores. 

Nota de Blanca: lo reformulo, pero pienso que lo debiera de haber formulado en conjunto con el #40

**Comment by BlancaCC** [comment]
Este issue debió de cerrarse con el PR #67
