### ISSUE TITLE
[MFNAUA] Definiciones 2.1 - 2.5

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#40]
Es necesario escribir las definiciones siguientes (El número se corresponde al número dentro de artículo) : 
2.1 Abstracción de una red neuronal.
2.2 Abstracción red neuronal una capa oculta.
2.3 Función de activación. 
2.4 Abstracción red neuronal multicapa. 
2.5 Sigma álgebra de borel.

Cabe destacar que estas no son todas las definiciones pendientes.

**Comment by BlancaCC** [comment]
Este issue se reformular a que es necesario establece una abstracción de las redes neuronales con el objetivo de poder trabajarla de manera formal

**Comment by BlancaCC** [comment]
Se entrega a revisión el capítulo 3: Redes neuronales multicapas son aproximadores universales. 
Esta entrega comprenden desde la introducción hasta la demostración del lema A.1 (paper en que se basta el capítulo). 
Se han eliminado de la entrega las secciones que no desean ser revisadas. 
[tfg Día 02-02-2022.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/7986807/tfg.Dia.02-02-2022.pdf)

**Comment by JavierMeri** [comment]
Estoy en ello. Lo he leído muy en diagonal pero tiene muy buena pinta. En cuanto pueda mando todos los comentarios y correcciones.

**Comment by BlancaCC** [comment]
Este issue debió de cerrarse con el PR #67
