### ISSUE TITLE
[DUDA] Sobre cómo traducir "Multilayer Feedforward Networks"

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#41]
No he encontrado una traducción que me guste de *Multilayer Feedforward Networks*
Las opciones que he barajado han sido: 
1. Mantener tal apelativo sin traducirlo: "Multilayer Feedforward Networks". 
2. Híbrido español inglés: Redes neuronales feedforward multicapas.
3. Redes neuronales multicapas prealimentadas (no lo he escuchado en mi vida, pero en la wikipedia le llaman así https://es.wikipedia.org/wiki/Red_neuronal_prealimentada 😅)

Agradecería una retroalimentación sobre la referencia que consideréis más apropiada. Yo esto entre la 1 y la 2.

**Comment by JavierMeri** [comment]
La solución a este problema como siempre va en gustos. Una vez elegido el nombre (estoy de acuerdo en que las opciones 1 y 2 son mucho más razonables), como es largo, resulta incómodo repetirlo. Hay varias opciones para evitar escribirlo una y otra vez. Las más simples son:
- Usar un acrónimo: MFN o RNFM según elijas la opción 1 ó 2. Esto se fijaría en la presentación de las redes neuronales y se usaría a partir de ese momento.
- En la presentación de esas redes neuronales decir una frase del tipo "la mayoría (o todas si es el caso) de las redes neuronales a las que se va a hacer referencia en el trabajo son de este tipo y nos referiremos a ellas simplemente como redes neuronales. La referencia a otro tipo de redes neuronales será especificada en su caso." Yo me decantaría por esta opción

**Comment by BlancaCC** [comment]
@JavierMeri De acuerdo, muchas gracias Javier 😊

Añadiré el comentario del acrónimo y creo que utilizaré la opción 1.
