### ISSUE TITLE
Explicación de la metodología usada en el trabajo

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#42]
Es necesario dar una descripción y explicación de la metodología usada. 
Que se recoge en los siguientes enlaces: 

- Artículo:  https://arxiv.org/abs/2104.12545
- Lineas generales: https://jj.github.io/que-es-un-trabajo-fin-de-x/tf.html

**Comment by JJ** [comment]
Como *tribunal de TFG*, *necesito* conocer la metodología que usa la estudiante para *evaluar la rúbrica correspondiente*. Recuerda, siempre que se resuelve un problema se resuelve *para alguien*
