### ISSUE TITLE
Construcción técnica de las redes neuronales

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#43]
Como *Javier y JJ* es necesario explicar cómo se definen, construyen y actualizan las redes neuronales de una manera técnica. El objetivo de este hito será tener claro cuáles son las herramientas de trabajo y principal objeto del estudio.

**Comment by JJ** [comment]
Necesario explicar, ¿a quién? Recuerda que cuando se resuelve un problema, se resuelve siempre *para alguien*. Puede ser en este caso la programadora, pero si la programadora hace eso tiene que tener siempre a la vista la usuaria final (la que quiere redes neuronales en su móvil de hace 3 años)

**Comment by BlancaCC** [comment]
Para un perfil técnico y científico es necesario explicar cómo se definen, construyen y actualizan las redes neuronales. El objetivo de este hito será tener claro cuáles son las herramientas de trabajo y principal objeto del estudio.

**Comment by JJ** [comment]
No te olvides en ese caso definir los perfiles de usuarios de los diferentes productos finales. Puedes usar la [metodología personas](https://www.interaction-design.org/literature/article/personas-why-and-how-you-should-use-them) o cualquier otra, pero las historias de usuario no son nada si no tienes claro quién es el usuario.

**Comment by BlancaCC** [comment]
Vale, gracias. Una pregunta ¿Dejo escrito los perfiles en algún lado concreto? 
A mi parecer los perfiles son: 
- Tribunal del TFG
- Lector, con conocimientos técnicos y científicos. 
¿Me dejo alguno más?

**Comment by JJ** [comment]
Esa es una de las cosas que tienes que desarrollar precisamente en el TFG... Como te digo, evidentemente tiene que haber alguien que quiera entrenar RNs en su dispositivo personal, pero puede haber alguno más. Los usuarios están siempre definidos por los beneficios que van a obtener del producto (y los problemas que eso plantea a nivel de proyecto). Por eso las historias de usuario son siempre Como usuario (perfil x), quiero (este es el beneficio que voy a obtener) en el contexto (el que sea).
