### ISSUE TITLE
Estudio de funciones que no sean medibles

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#45]
Como matemática recalcitrante me gustaría investigar un poquito más sobre las funciones que no sean medibles, esto se debe a que según el teorema de aproximación universal este tipo patológico de funciones no pueden ser aproximadas.
Un estudio de ellas podría ser interesante por los siguientes motivos: 
- ¿Son un conjunto que verdaderamente supone una limitación a nivel de usuario?
- ¿Podría de alguna manera definirse una técnica que las contemplara? Esto supondría una mejora o "optimización" de las redes neuronales. 

Bibliografía que se puede consultar (la he leído en diagonal) es el libro *Probability and Measure* de Billingsley  capítulo 13 página 182 (https://www.colorado.edu/amath/sites/default/files/attached-files/billingsley.pdf)

**Comment by JJ** [comment]
> Como matemática recalcitrante me gustaría investigar un poquito más sobre las funciones que no sean medibles, esto se debe a que según el teorema de aproximación universal este tipo patológico de funciones no pueden ser aproximadas. Un estudio de ellas podría ser interesante por los siguientes motivos:
> 
>     * ¿Son un conjunto que verdaderamente supone una limitación a nivel de usuario?
> 
>     * ¿Podría de alguna manera definirse una técnica que las contemplara? Esto supondría una mejora o "optimización" de las redes neuronales.

Ok, esto lo enlaza con el objetivo principal del proyecto, pero tienes que crear una historia de usuario que refleje ese objetivo principal del proyecto, y enlazar esto con esa historia de usuario (así como otros issues relacionados).

Recuerda también que los issues se cierran sólo cuando se cumplan los criterios de aceptación. En este caso, hay más o menos unos criterios de aceptación implícitos, pero para hacerlos explícitos deberías crear un PR y que lo aceptara @javiermeri

(Y recuerda también que todos los issues deben estar asignados a un milestone).

**Comment by BlancaCC** [comment]
@JJ Sí tienes razón, crearé mañana las historias de usuario y la próxima vez explicitaré el criterio de aceptación, gracias 😊

Hay un montón de issues antiguos que no tienen mucho sentido, si os parece bien los cierro directamente y si es necesario se reformulan

**Comment by JavierMeri** [comment]
Desde el punto de vista matemático las funciones no medibles y los conjuntos no medibles llaman la atención y dedicarles tiempo seguro que es enriquecedor. Sin embargo, me cuesta creer que una función no medible pueda modelizar algún problema abordable. Las funciones continuas son predecibles en teoría porque puedes estimar el error que cometen a priori (si no tienes control sobre la dependencia entre epsilon y delta la estimación del error se queda a nivel teórico, es por ello que en muchos problemas concretos se usan clases de funciones más restrictivas: derivables, lipschitzianas, hölder continuas...), las funciones medibles son como su nombre indica susceptibles de ser medidas en teoría. Los procesos de paso al límite en una clase de funciones cobran sentido cuando tienes la garantía de que el límite se queda en tu clase (complitud) o, por lo menos, en una clase más amplia que puedes manejar. La clase de las funciones medibles se puede dotar de una topología vectorial razonable pero no es normable y eso te lleva a trabajar en el ambiente de los espacios vectoriales topológicos (la generalización más amplia de los espacios de Banach). La clase de las funciones no medibles no tiene estructura vectorial (aunque es enorme y contiene espacios vectoriales gigantescos cuando se le añade el cero) lo que la deja fuera incluso del ambiente de los espacios vectoriales topológicos. El primer paso sería ver si hay alguna topología aceptable en la clase de las funciones no medibles, el problema es que quedará fuera de la teoría de Análisis Funcional y ninguna de las técnicas sobre las que estás leyendo serán aplicables.

**Comment by BlancaCC** [comment]
@JavierMeri Muchas gracias por el comentario 😊

Creo entonces que quizás interese comentar algo similar a lo que nos has transmitido pero sin dedicarle mucho tiempo.

**Comment by JavierMeri** [comment]
Una posibilidad muy seria de generalizar la gran mayoría de los resultados conocidos sobre convergencia de redes neuronales es trabajar en el ambiente de las distribuciones. El espacio de distribuciones contiene a todas las funciones decentes (continuas, integrables de cualquier exponente, ...), a las medidas y a otros muchos objetos que se pueden ver como funciones generalizadas. Se trata de un espacio vectorial que se puede dotar de una topología natural que es vectorial y completa. Tiene gran utilidad a la hora de encontrar solución a problemas en los que se busca una función y los métodos clásicos no dan información. Para que te hagas una idea, cualquier sistema lineal de ecuaciones en derivadas parciales con coeficientes constantes tiene solución en el ambiente de las distribuciones. En mi opinión este enfoque va mucho más allá del nivel de un TFG, sería perfecto para un TFM muy ambicioso. Lo primero que se necesitaría es un curso de análisis funcional avanzado para entrar en el ambiente general de los espacios vectoriales topológicos y empezar a manejar las propiedades del espacio de distribuciones.

**Comment by BlancaCC** [comment]
@JavierMeri Qué interesante Javier, gracias por la información, está bien tener la idea aunque se escape del alcance. 

Voy a terminar de escribir lo esencial y luego vemos por dónde podemos probar 😊
