### ISSUE TITLE
Incluir en la metodología el registro de las horas de trabajo

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#46]
Un proyecto de ingeniería siempre requiere una estimación de costes, y como tal debe incluir el tiempo empleado en el mismo.
Lo ideal es que uses un CSV en este mismo repositorio, que asigne horas a issues y por tanto a milestones, y que permita sacar gráficos bajo demanda. Si no, simplemente una hoja de cálculo donde se acumulen las horas de trabajo, posiblemente por fecha, es suficiente.

**Comment by BlancaCC** [comment]
@JJ En mi afán de recopilar datos he  estado haciendo esto, no sé si vale 
https://docs.google.com/spreadsheets/d/1TCcKQIKjKW9sMSU2f6obN9gHgv3c8UEdjmONkBlv42M/edit#gid=1582119647

**Comment by JJ** [comment]
@BlancaCC Sí, claro que vale. Lo único que tienes que hacer es tratar de asignarlo a algún milestone.
