### ISSUE TITLE
[HU01] Optimización redes neuronales

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#48]
Como *Rosa* me gustaría que se encontrara alguna optimización en las redes neuronales, ya sea: 
- Necesidad de arquitecturas menos potentes. 
- Mayor precisión para misma arquitectura. 
- Resolver nuevos problemas.

**Comment by JJ** [comment]
OK, esto complementa a #51 porque sería el punto de vista del usuario final, pero antes tendría que pasar por varios productos mínimamente viables.
