### ISSUE TITLE
[HU05] Presentación ante tribunal

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#49]
Como *Mayte y Pablo*, miembros del tribunal, queremos corregir un trabajo fin de grado bien hecho. 
Bajo el contexto de evaluación la memoria debe de cumplir una serie de requisitos imprescindibles:

1. Declaración explícita firmada en la que se asume la originalidad del trabajo, entendida en el sentido de que no ha utilizado fuentes sin citarlas debidamente. Esta declaración se puede descargar en la web del Grado (matemáticas). 
2. Un índice detallado de capítulos y secciones.
3. Un resumen amplio en inglés del trabajo realizado (se recomienda entre 800 y 1500 palabras).
4. Una introducción en la que se describan claramente los objetivos previstos inicialmente en la propuesta de TFG, indicando si han sido o no alcanzados, los antecedentes importantes para el desarrollo, los resultados obtenidos, en su caso, y las principales fuentes consultadas.
5. Una descripción de la metodología. 
6. Un estado del arte y diseño. 
7. Estimación de los costes. 
8. Análisis de las prestaciones (este requisito "es informático" y está estrechamente ligado con el 4)
9. Una bibliografía final que incluya todas las referencias utilizadas.

**Comment by JJ** [comment]
Una historia de usuario debe siempre suponer un beneficio para el usuario. Si esta es *la* HU del tribunal, debes decir qué debe obtener el tribunal de este trabajo.

**Comment by BlancaCC** [comment]
@JJ ,  perdón logro entender a qué te refieres o qué matiz me quieres dar. Para mí lo que representa esta HU es que al tribunal se le entrega un proyecto evaluable en forma de memoria y que además que debe de tener una serie de requisitos...

**Comment by JJ** [comment]
Es simplemente un cambio de formulación. "En el contexto de evaluación de la memoria, necesito que la memoria cumpla los siguientes requisitos..."

**Comment by BlancaCC** [comment]
Va a haber que reajustas las historias de usuario a estos requisitos https://grados.ugr.es/informaticaymatematicas/pages/infoacademica/tfg/formato/formato_memoriatfgdg

cuando se redactó la HU no se encontró esta fuente
