### ISSUE TITLE
[HU03] Estudio redes neuronales

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#50]
Como Javier me gustaría que la memoria fuera un estudio de calidad de las redes neuronales, respondiendo de manera  autocontenida, clara, rigurosa y precisa a preguntas como:
- ¿Qué son las redes neuronales?
- ¿Cómo se construyen?
- ¿Para qué sirven?
- ¿por qué funcionan?

**Comment by JJ** [comment]
Este estudio, como indico en #81, tiene que estar siempre en relación con los objetivos del proyecto. Toda HU tiene también que expresar un beneficio que estaría, naturalmente, en relación con el mismo. Ahora mismo no expresa un beneficio, sino un producto que se desea obtener con la misma.
Posible reformulación:
> Como Javier, dado que se ha probado que las redes son aproximadores universales, deseo entender las hipótesis básicas que han llevado a esa prueba con el objetivo de  cambiarlas para obtener pruebas más precisas que permitan crear algoritmos de entrenamiento o de explotación más eficientes en capacidad computacional o en cualquier otro aspecto (mejoria, consumo energético)
