### ISSUE TITLE
[HU04] Indagar y experimentar sobre redes neuronales

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#51]
Como *Javier y JJ* me gustaría plantear nuevas hipótesis para conocer en mayor profundidad, aclarar limitaciones, particularizar o abstraer en cualquier aspecto de las rrnn actuales.

**Comment by JJ** [comment]
No veo mucha diferencia con (la nueva formulación) de la #50. Y también queda un poco difuso. "Conocer" no es un beneficio.
Sí podrías reconvertirla en una HU práctica. El beneficio que se debería obtener, en este caso, sería tener una implementación práctica de algoritmos de entrenamiento de redes neuronales (o machine learning en general) que permitan obtener con recursos limitados resultados aceptables.
