### ISSUE TITLE
Añadir sección de preprocesado de datos 

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#55]
Como matemática considero que es necesario añadir un capítulo o sección dedicado al preprocesado de datos, tras la sección dedicada al machine Learning. 
Los motivos son múltiples: 
1. Compresión y contexto de las redes neuronales. #50
2. Ayuda a la hora de clarificar las hipótesis razonables que verifiquen los datos a la hora de optimizar. #51 

1. No olvidemos que se está trabajando dentro del campo de la ciencia de datos/machine Learning, donde las redes neuronales no son más que un modelos más de los que elegir dentro de la serie habitual procesos:
(i) Objetivo por el que se pretende trabajar con los datos.
(ii) Recuperación de los datos. 
(iii) Preparación de los datos.
(iv) Exploración.
(v) Modelado de los mismo (Aquí es donde aparecen las redes neuronales).
(vi) Entrenamiento + experimentos y ajuste parámetros...

2. Por ejemplo se podría pedir que las variables no estén correladas a cierto nivel.  

Se aceptará este issue cuando haya sido escrito y validado por alguno de los tutores, 
no se pretende profundizar en demasía en el tema, si no comentar aspectos como: 
(a)Limpiado de los datos: 
  - Errores en los datos
  - Valores imposibles
  - Valores perdidos
(b) Transformación de los datos: 
 - Reducción de dimensión 
 - Agregación de datos 
 - Extrapolación de los datos

La bibliografía de la que estoy investigando son libros de carácter técnico como: 
- Introducing data Science, por Hielen, Meysman y Ali de editoral Manning
- Varios de la editorial O'Reilly como puede ser "Práctica Statistics for Data Scientists".

**Comment by JJ** [comment]
No parece que esté bien encajado en este hito.
