### ISSUE TITLE
Duda lema A.2

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#61]
Buenos días, 
el lema A2 me tiene mareadísima (y mira que parecía inocente), explico la situación. 
Os adjunto un borrador con la demostración y la prueba del paper, indicando los puntos conflictivos en rojo. En el que la parte final se me ha atrancado rematar bien una desigualdad y ya no sé cómo seguir. Ese problema puede radicar de un paso anterior y que por eso no consiga hilar bien: 
Hay dos puntos que pueden ocasionar esto: 
1. Intercambio los signos en una definición porque pienso que no está bien de esa manera.
(Decisión que me genera un gran conflicto ¿Cómo va a estar "mal" la demostración de un paper tan trillado?)
2. Hay una definición que se escribe como a/bc y aunque la interpretación rigurosa debiera ser
(a/b)c he optado por tomarlo como a/(bc).

[duda Lema 2.A.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8023463/duda.Lema.2.A.pdf)

Agradecería que me echarais una mano, para poder continuar con  #40

**Comment by BlancaCC** [comment]
@BlancaCC He exportado sin querer mal el fichero, este sería el completo

**Comment by JJ** [comment]
A ver, pone sqashing en vez de squashing. Así que yo qué sé...

**Comment by BlancaCC** [comment]
Revisando el documento que he mandado en un apartado (que no influye en el problema), no he sido consiste con la notación de la hipótesis(2) 😅, dejo aquí captura del error por si da lugar a confusión.
<img width="1144" alt="Captura de pantalla 2022-02-08 a las 12 49 24" src="https://user-images.githubusercontent.com/32298296/152981693-507a5070-123d-4be8-b3b7-fa280a2228c9.png">

Pero vamos, que se puede ignorar perfectamente.

**Comment by BlancaCC** [comment]
@JavierMeri No hay prisa, no te preocupes

**Comment by JavierMeri** [comment]
Tienes toda la razón en los dos comentarios sobre la demostración. Lo subrayado en verde hay que definirlo como tu lo has hecho y lo subrayado en amarillo está incorrecto, se deben intercambiar los valores tal como propones. La demostración deja muchos detalles al lector, estaría bien darle una vuelta completa para hacer una presentación clara. Si quieres podemos quedar por meet y comentarlo, con un par de ideas sencillas creo que se puede escribir la demostración de los detalles sin que sea demasiado farragosa.

**Comment by BlancaCC** [comment]
@JavierMeri Gracias Javier por revisarlo

**Comment by BlancaCC** [comment]
La conclusión ha sido: 
Se aceptan los cambios propuestos del paper propuesto al abrir el issue. 
y además se define q de tal manera que cumpla que 1/p < epsilon/4
de esta manera la ecuación conflictiva queda (adjunto imagen):
 
![corrección_Lema ](https://user-images.githubusercontent.com/32298296/153035527-f211bae7-1dfd-4c59-9085-749b6581b2b1.jpeg)

(Con la visión de intervalos y diámetro se ve mucho más claro y rápido, muchas gracias Javier, aunque sea de Lebesgue 😜)

Cerraré el issue con el commit que contenga el lema bien escrito.
