### ISSUE TITLE
¿Añadir apéndice con código?

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#62]
Como alumna del TFG y teniendo siempre presente #49 
he usado código para generar ciertas imágenes, ¿He de añadir un apéndice en la memoria con el mismo?
¿Todo el código que escriba debo añadirlo? ¿O solo el relevante? 

En un principio, salvo que sea relevante para la memoria no lo voy a añadir porque quedaría una memoria casi infinita. Pero me gustaría que me confirmarais qué es lo que debo hacer.

**Comment by JJ** [comment]
Simplemente enlaces a lo que sea pertinente desde el texto; con eso es suficiente.

**Comment by BlancaCC** [comment]
Muchas gracias, cerraré issue en con el próximo commit
