### ISSUE TITLE
¿Qué hacer cuando una fórmula inline de laTEX salta de línea?

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#68]
Me ha surgido varias veces la siguiente duda:
Supóngase que se está escribiendo una fórmula inline en un párrafo y por llegar al final de la linea se sigue escribiendo en la siguiente: 
Pongo dos ejemplos
Ejemplo primero: 
<img width="554" alt="Captura de pantalla 2022-02-16 a las 17 15 48" src="https://user-images.githubusercontent.com/32298296/154309127-030fa91e-9759-4955-8834-29c0850ba5b7.png">
Ejemplo segundo:
<img width="554" alt="Captura de pantalla 2022-02-16 a las 17 40 43" src="https://user-images.githubusercontent.com/32298296/154313504-04843eef-a3ee-4fba-9089-0bf8ac6f77a1.png">

En estos casos  he estado haciendo es dejarlos tal cual ¿sería correcto?

**Comment by JJ** [comment]
Supongo que no ponerla inline.
