### ISSUE TITLE
Duda: en la memoria pseudo código o Julia

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#69]
Agradecería si me pudierais responder a esta cuestión. 
Contexto: Estoy explicando el algoritmo de *forward propagation* en redes neuronales. 
¿escribo el algoritmo en pseudo código o directamente lo escribo en Julia?

Por una parte entiendo que debe de explicarse un algoritmo sin introducir conceptos adicionales como reglas de un lenguaje, pero no  existe un estándar de pseudo código y lenguajes de alto nivel como Julia o Python permiten una comprensión directa (yo diría que cualquier persona que incluso no haya programado en esos lenguajes los entiende).

Yo lo pondría directamente en estos lenguajes, pero no sé si existe alguna convención al respecto.

**Comment by BlancaCC** [comment]
Entiendo JJ pero en este caso no lo veo tan claro, 
La duda surge en la realización de #43 que a su vez trata de resolver la HU #50 
Por lo tanto el usuario al que va dirigido es Javier, simplemente quiere entender el algoritmo, **luego a priori, por hacerlo todo lo abstracto posible sería pseudocódigo...**
 Sin embargo yo diría que lo conseguiría tanto con Julia como con pseudo código. Entonces avancemos un paso más para ver qué nos puede interesar: 
HU #50 pertenece al milestone 2  de estudio de las redes neuronales, el siguiente milestone sería el de plantear nuevas hipótesis de optimización, concretamente la HU #51 . Por lo tanto será necesario experimentar y tener una implementación ya escrita sería necesario. Esto inclina la balanza hacia Julia, pero si tenemos presente el último miliestone, que consiste en presentar la memoria ante un tribunal #49 ¿tiene este tribunal algún requisito que desconozco sobre utilizar código para explicar? ¿se utiliza código de un lenguaje en artículos científicos? de ahí la pregunta. 

No me extrañaría que hace unos años no se utilizara código de un lenguaje concreto no solo por mantener el problema de manera genérica, sino  porque introducían sintaxis especial alejada del lengua matemático, pero con algunos lenguajes...

**Comment by JJ** [comment]
Recuerda que te comenté la metodología de "personas", que define a un posible usuario hasta el punto de listar sus habilidades cognitivas y conocimientos. ¿la persona para la que estás resolviendo el problema es capaz de entender la sintaxis de Julia?

> Una pregunta anterior sería si esa persona *necesita* las explicaciones en código o seudocódigo, claro. Igual habría que partir de ahí.

Si al final lo vas a hacer para incluirlo en la memoria, que la va a leer el tribunal, ¿el tribunal va a mirarse el seudocódigo o en Julia? Por eso te digo que es importante definir tanto las "personas" como los problemas que quieres resolver.

**Comment by BlancaCC** [comment]
De acuerdo JJ, gracias por todo. 
Cerraré este issue con el commit que añade el código
