### ISSUE TITLE
Usa nombre estándar para las ramas

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#74]
Las ramas tienen nombres que indican qué es lo que se está haciendo, no un nick y un número. No se debe usar # en el nombre de una rama, no es estándar.

Una forma estándar sería tarea-probar-teorema-xx

**Comment by BlancaCC** [comment]
Muchísimas gracias @JJ  por abrirme el issue, ahora se ha quedado todo más claro  :) 

<img width="1380" alt="Captura de pantalla 2022-03-05 a las 12 49 42" src="https://user-images.githubusercontent.com/32298296/156881912-dc4a12dd-58f1-408a-971b-3b9b477b14d1.png">
