### ISSUE TITLE
Como alumna del TFG necesito ayuda sobre cómo añadir notas bonitas a los márgenes

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#77]
Con el fin de comenzar la resolución de #73 necesito implementar un comando para escribir notas en los márgenes. Podría utilizar el que indicó @JJ  en ese mismo issue, sin embargo me gustaría que fueran en un marco con colores, ya que de esta manera podremos separa dos tipos de notas, aquellas que son aclarativas sobre el contenido matemático y las que destacan un teorema relevante que puede ser utilizado para formula una hipótesis de optimización. Además creo que el color le puede aportar estética al TFG. Sin embargo llevo tres días peleándome y no hay manera, es por es ello que  os pregunto, porque quizás se os ocurre una solución. 

La situación es la siguiente: 
0. El margen es muy pequeño como para que leer en los márgenes sea gustoso y sin recargarlo tampoco resulta del todo agradable (adjunto imagen)
<img width="1035" alt="Captura de pantalla 2022-03-10 a las 9 15 46" src="https://user-images.githubusercontent.com/32298296/157618142-dd5ff3c3-9666-47a8-ba50-e8d7dbb346b7.png">

1. Es necesario por tantoo ampliar el margen y darle algo de vidilla a la nota con colores. No quiero ampliar el tamaño de margen de todas las páginas. Luego solo debería de modificarse en aquellas que utilicen las notas de los márgenes. 
<img width="1282" alt="Captura de pantalla 2022-03-10 a las 9 01 42" src="https://user-images.githubusercontent.com/32298296/157617025-ff83a080-a114-4ed5-a215-c9dc6d4bd4da.png">

2. Una de las opciones que he probado es utilizar el comando `newgeometry` que produce un salto de página (adjunto captura del resultado). 

<img width="1282" alt="Captura de pantalla 2022-03-10 a las 9 02 19" src="https://user-images.githubusercontent.com/32298296/157617049-bec63e42-1390-4be8-ac13-84ac38db0cc4.png">

**Comment by JJ** [comment]
Siempre en un producto mínimamente viable tienes que optar por lo primero que cumpla las expectativas, aunque no sea estéticamente agradable o perfecto. Así que 0 está bien por mi.

**Comment by BlancaCC** [comment]
De acuerdo JJ, gracias por responder

**Comment by JavierMeri** [comment]
También veo bien 0. Creo que no merece la pena cambiar el tamaño de los márgenes
