### ISSUE TITLE
Creación biblioteca redes neuronales

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#80]
Con el objetivo de resolver #79 y seguir un desarrollo ágil #65 se deberá de crear una biblioteca que: 

1.a Contenga la implementación de las función de activación presentadas a lo largo del estudio de RRNN.
1.b Test que se cerciore de que devuelven valores reales. 
2.a Una estructura que represente una red neuronal.
2.b. Un método de evaluar una red neuronal utilizando *forward propagation*.
2.b.i Un test de que se evalúa correctamente. 
2.c Un método para actualizar los pesos de la red neuronal usando *backpropagation*
2.c.i Un test que se cerciore de la corrección del algoritmo de *backpropagation*

**Comment by JJ** [comment]
Un issue siempre tiene que formular un problema, no una solución como "crear una biblioteca". çal formular un problema, no se fija la solución en una, o en varias, o en las diferentes partes que va a tener la biblioteca.
El cuerpo del issue es más o menos correcto; expresa las diferentes partes que debería tener. Pero recuerda siempre issue == problema, no tarea ni entregable (los entregables tienen que estar en los hitos)
Por supuesto, tampoco encajaría bien en el hito donde está, salvo que contribuya al producto mínimamente viable por alguna razón.

**Comment by JJ** [comment]
Si el objetivo es resolver otro issue, no se crea un issue adicional, se va directamente al código.
