### ISSUE TITLE
Es necesario clarificar el entregable del hito 1

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#81]
Primero, porque se puede eternizar. Un "estudio" no tiene por qué acabar nunca. En concreto, hace falta saber qué concluirá el estudio o qué es lo que abarca el estudio.
En general, debe estar relacionado con los objetivos del trabajo. Dado que se trata de buscar caminos de mejorar las prestaciones en el entrenamiento y desempeño de redes neuronales desde un punto de vista teórico, mi sugerencia es que debería concluir cuando se encontraran formas de
* Acotar el tamaño o la precisión de los pesos u otros parámetros de la red neuronal
* Alguna forma de acelerar la convergencia, si es que se va a optar por un método de descenso de gradiente.
* En general, cualquier hipótesis que se se pueda relajar o cambiar en el camino de reducir el espacio de búsqueda de posibles redes neuronales o de los pesos de las mismas.

Este hito, además, terminaría este fin de semana. Sería también cuestión de reorganizar y mover issues a los siguientes si es que no entran en ese producto mínimamente viable.

**Comment by BlancaCC** [comment]
A priori había pensado que este hito era solo para *recopilar información* y la parte de buscar resultados estaba más dirigida al hito 2. 
Sin embargo por tu comentario me he dado cuenta que estaba mal enfocada, porque no es un proceso lineal si no cíclico. 
de documentación, formulación de hipótesis y vuelta a la documentación. 
Ya está reescrito, los cambios que he aplicado: 
- Destacar que el objetivo es encontrar resultados teóricos que optimicen las redes neuronales. 
- Cambio  fecha límite para Semana Santa. 

Es necesario además reenfocar el [hito 2](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/milestone/4)
, este cuantificará experimentalmente las propuestas dilucidadas del hito 1.
