### ISSUE TITLE
Es necesario clarificar el entregable del milestone 2

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#82]
En [este caso](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/milestone/4) conviene decir exactamente qué es lo que se va a tener al terminar. ¿Un teorema de aproximación con menos requisitos? ¿Límites un poco más precisos? ¿Un algoritmo de entrenamiento que permita llegar a un resultado aceptable más rápidamente?

**Comment by BlancaCC** [comment]
Como comento en #81 la reescritura del [hito 1](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/milestone/2) ha conducido a reenfocar el [hito 2](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/milestone/4) que ahora consiste en esencia en una constatación experimental de los resultados obtenidos en el hito 1.
