### ISSUE TITLE
Crear milestones más allá del 2

### ISSUE THREAD

**Issue by JJ** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#83]
Aunque hay uno creado sin número, en realidad se trata del producto final, y antes hay que implementar las hipótesis probadas con el milestone 2. En concreto, habría que hacer 2 milestones adicionales (con el último opcional)
- Implementar las tesis probadas en un algortimo, comparando siempre con el estado del arte para probar que efectivamente se crean métodos más democráticos en algún aspecto. A la vez, desarrollar o adoptar una medida de comparación que tenga en cuenta ese uso inferior de recursos (lo que es fácil si es simplemente que tarde menos, pero no tan fácil si se trata de que consuma memos memoria o menos energía).
- Llevar a cabo una serie de pruebas con conjuntos estándar (Kaggle, PROBEN1), probando si hay degradación en resultados o si trabaja bien en un muestrario amplio de posibles problemas (este seguramente no dará tiempo).
- Crear una demo en un sistema real con relativamente pocos recursos (móvil, raspberry pi) y ver qué tipo de adaptaciones de la implementación tienen que hacerse para este dispositivo.

**Comment by BlancaCC** [comment]
@JJ , atendiendo a este comentario y a los issue #81 y #82 he reorganizado los milostones de la siguiente forma: 
(Son menos milestones de los que propones, puede que se me esté escapando algún detalle, por favor corrígeme si es así): 

- El [hito 1](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/milestone/2) consiste en la búsqueda y fundamentación teórica de hipótesis de optimización. 

- El [hito 2](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/milestone/4) comprende:
La constatación experimental de las hipótesis del hito 1, seguramente será necesario para esta prueba la implementación de algoritmos, luego el hito adicional primero estaría incluido. 

Respecto al dos propuesto ¿No estaría incluido en los tests? Es decir, tenía pensado primero hacer experimentos con datos sintéticos y luego con reales

- El último milestone lo he incluido como [hito 3](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/milestone/7)

En cuanto me digas si apruebas esta estructura cierro el issue

**Comment by JJ** [comment]
OK, lo veo correcto.
