### ISSUE TITLE
Añadir algún símbolo visual que destaque aportaciones propias 

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#91]
Debe de quedar claro para #49 lo que es recopilación bibliográfica y aportaciones propias, luego debería de añadir algún código visual, como por ejemplo una raya amarilla en un lateral, o un color de fondo distinto para destacar el contenido original.

**Comment by BlancaCC** [comment]
@JJ , @JavierMeri  ¿Veis oportuno destacar de alguna manera las demostraciones que estaban mal hechas en el artículo de convergencia y nuestra corrección?

**Comment by JavierMeri** [comment]
> @JJ , @JavierMeri ¿Veis oportuno destacar de alguna manera las demostraciones que estaban mal hechas en el artículo de convergencia y nuestra corrección?

Creo que no es necesario destacar los errores. Puedes destacar que has ampliado o hecho con más detalle algunas demostraciones. Aunque eso se presupone como parte del trabajo de un TFG, porque un artículo está escrito de manera escueta y asumiendo que el lector conoce muchas cosas
