### ISSUE TITLE
Eliminar TODOs

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/TFG-Estudio-de-las-redes-neuronales#93]
Hay por el texto algunos TODOs y cuestiones abiertas, deberían de eliminarse y las cuestiones abiertas, de ser relevantes transformarse en issue o PR

**Comment by JJ** [comment]
En general, no es una buena idea poner TODOs en el texto, es mucho mejor abrir issues. Cuando cierres esto, sería conveniente que lo hicieras así.
